// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gocache.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_gocache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_gocache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_gocache_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ResponseForGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForGet) Reset() {
	*x = ResponseForGet{}
	mi := &file_gocache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForGet) ProtoMessage() {}

func (x *ResponseForGet) ProtoReflect() protoreflect.Message {
	mi := &file_gocache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForGet.ProtoReflect.Descriptor instead.
func (*ResponseForGet) Descriptor() ([]byte, []int) {
	return file_gocache_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseForGet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ResponseForDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForDelete) Reset() {
	*x = ResponseForDelete{}
	mi := &file_gocache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForDelete) ProtoMessage() {}

func (x *ResponseForDelete) ProtoReflect() protoreflect.Message {
	mi := &file_gocache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForDelete.ProtoReflect.Descriptor instead.
func (*ResponseForDelete) Descriptor() ([]byte, []int) {
	return file_gocache_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseForDelete) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ResponseForSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForSet) Reset() {
	*x = ResponseForSet{}
	mi := &file_gocache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForSet) ProtoMessage() {}

func (x *ResponseForSet) ProtoReflect() protoreflect.Message {
	mi := &file_gocache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForSet.ProtoReflect.Descriptor instead.
func (*ResponseForSet) Descriptor() ([]byte, []int) {
	return file_gocache_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseForSet) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gocache_proto protoreflect.FileDescriptor

const file_gocache_proto_rawDesc = "" +
	"\n" +
	"\rgocache.proto\x12\x05proto\"G\n" +
	"\aRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"&\n" +
	"\x0eResponseForGet\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\")\n" +
	"\x11ResponseForDelete\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"*\n" +
	"\x0eResponseForSet\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x99\x01\n" +
	"\aGoCache\x12,\n" +
	"\x03Get\x12\x0e.proto.Request\x1a\x15.proto.ResponseForGet\x12,\n" +
	"\x03Set\x12\x0e.proto.Request\x1a\x15.proto.ResponseForGet\x122\n" +
	"\x06Delete\x12\x0e.proto.Request\x1a\x18.proto.ResponseForDeleteB\x04Z\x02./b\x06proto3"

var (
	file_gocache_proto_rawDescOnce sync.Once
	file_gocache_proto_rawDescData []byte
)

func file_gocache_proto_rawDescGZIP() []byte {
	file_gocache_proto_rawDescOnce.Do(func() {
		file_gocache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gocache_proto_rawDesc), len(file_gocache_proto_rawDesc)))
	})
	return file_gocache_proto_rawDescData
}

var file_gocache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gocache_proto_goTypes = []any{
	(*Request)(nil),           // 0: proto.Request
	(*ResponseForGet)(nil),    // 1: proto.ResponseForGet
	(*ResponseForDelete)(nil), // 2: proto.ResponseForDelete
	(*ResponseForSet)(nil),    // 3: proto.ResponseForSet
}
var file_gocache_proto_depIdxs = []int32{
	0, // 0: proto.GoCache.Get:input_type -> proto.Request
	0, // 1: proto.GoCache.Set:input_type -> proto.Request
	0, // 2: proto.GoCache.Delete:input_type -> proto.Request
	1, // 3: proto.GoCache.Get:output_type -> proto.ResponseForGet
	1, // 4: proto.GoCache.Set:output_type -> proto.ResponseForGet
	2, // 5: proto.GoCache.Delete:output_type -> proto.ResponseForDelete
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gocache_proto_init() }
func file_gocache_proto_init() {
	if File_gocache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gocache_proto_rawDesc), len(file_gocache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gocache_proto_goTypes,
		DependencyIndexes: file_gocache_proto_depIdxs,
		MessageInfos:      file_gocache_proto_msgTypes,
	}.Build()
	File_gocache_proto = out.File
	file_gocache_proto_goTypes = nil
	file_gocache_proto_depIdxs = nil
}
